Export keystore file to google drive
akroma-project/akroma-wallet-mobile pull request #85
Opened 2022-12-13 16:35 UTC by adonayvasquezz

[issue-72](https://github.com/akroma-project/akroma-wallet-mobile/issues/72)

## Description
- Users can export their wallet keystore file to their Google drive.

## To test
  1. Go to wallet
  2. Press the top right button.
  3. Select Wallet Settings.
  4. Press the top right button.
  5. Select export
  6. Select Export to Google drive button

<img width="337" alt="Captura de Pantalla 2022-12-13 a la(s) 10 33 43" src="https://user-images.githubusercontent.com/50288507/207390768-5ee82dad-7867-445c-8c16-83d2dedb049b.png">

2022-12-14 17:13 UTC, detroitpro commented
@Argude01 @adonayvasquezz - can you see why this failed on Bitrise.

I believe that once we have all the deployment/profiles/keys/assets in place - that bitrise builds should not fail unless we change something core.

2022-12-14 17:25 UTC, adonayvasquezz commented
> @Argude01 @adonayvasquezz - can you see why this failed on Bitrise.
> 
> I believe that once we have all the deployment/profiles/keys/assets in place - that bitrise builds should not fail unless we change something core.

Ok, yes something core changed, let me check

2022-12-15 14:40 UTC, cafadev requested changes
Nice job on this one @adonayvasquezz. Just asking you for small changes to make

2022-12-15 14:40 UTC, cafadev commented on src/screens/home/WalletSettingsScreen.tsx
> +    //console.log('Lista en drive ', await gdrive.files.list());
I think we can remove this commented code!

2022-12-15 14:40 UTC, cafadev commented on src/screens/home/WalletSettingsScreen.tsx
> +    const platformSetup = Platform.OS === 'android' ? { scopes: ['https://www.googleapis.com/auth/drive.file'] } : { iosClientId: '507652349383-rmhtbabce3ir7tk5pmv32j9qug0bfc9o.apps.googleusercontent
Can we set an `env` variable to store the `iosClientId`?

2022-12-15 15:17 UTC, adonayvasquezz commented on src/screens/home/WalletSettingsScreen.tsx
> +    const platformSetup = Platform.OS === 'android' ? { scopes: ['https://www.googleapis.com/auth/drive.file'] } : { iosClientId: '507652349383-rmhtbabce3ir7tk5pmv32j9qug0bfc9o.apps.googleusercontent
Yep, I'll setup the env variable

2022-12-15 18:40 UTC, adonayvasquezz commented on src/screens/home/WalletSettingsScreen.tsx
> +    const platformSetup = Platform.OS === 'android' ? { scopes: ['https://www.googleapis.com/auth/drive.file'] } : { iosClientId: '507652349383-rmhtbabce3ir7tk5pmv32j9qug0bfc9o.apps.googleusercontent
due the client id is not a security issue i put it in a constants file

2022-12-15 22:30 UTC, cafadev approved these changes

2022-12-15 22:30 UTC, merged