issue #84: Wallet buttons for receiving and send AKA
akroma-project/akroma-wallet-mobile pull request #86
Opened 2022-12-16 16:20 UTC by adonayvasquezz

[issue-84](https://github.com/akroma-project/akroma-wallet-mobile/issues/84)

## Description
- Add buttons to the wallet details section for receiving & send AKA
- Buttons in options menu for receiving and send AKA removed

<img width="334" alt="Captura de Pantalla 2022-12-16 a la(s) 10 12 13" src="https://user-images.githubusercontent.com/50288507/208142070-c4a61634-98de-4f04-807e-5dc8655ebf4f.png">

2022-12-20 21:08 UTC, cafadev requested changes
Looks great 👍🏼 . Just resolve the small changes.

2022-12-20 21:08 UTC, cafadev commented on src/components/DetailsScreenHeaderRight.tsx
>          showActionSheetWithOptions(
Can we place this function before the `return` ?. In order to keep the JSX easy to read.

2022-12-22 14:41 UTC, adonayvasquezz commented on src/components/DetailsScreenHeaderRight.tsx
>          showActionSheetWithOptions(
Yes, On it!

2022-12-22 16:22 UTC, cafadev commented
@adonayvasquezz help me to resolve the conflicts! Thank you! 👍🏼

2022-12-22 17:03 UTC, cafadev approved these changes

2022-12-22 17:03 UTC, merged